openapi: 3.0.3
info:
  title: SOA Lab1 Variant 43435
  version: '1.0.0'
  description: |
    Разработать спецификацию в формате OpenAPI для набора веб-сервисов, реализующего следующую функциональность:

    **Первый веб-сервис** должен осуществлять управление коллекцией объектов. В коллекции необходимо хранить объекты класса Person. Описание которого приведено ниже:
    ``` 
    public class Person {
      private Integer id; //Поле не может быть null, Значение поля должно быть больше 0, Значение этого поля должно быть уникальным, Значение этого поля должно генерироваться автоматически
      private String name; //Поле не может быть null, Строка не может быть пустой
      private Coordinates coordinates; //Поле не может быть null
      private java.time.ZonedDateTime creationDate; //Поле не может быть null, Значение этого поля должно генерироваться автоматически
      private Double height; //Поле может быть null, Значение поля должно быть больше 0
      private String passportID; //Строка не может быть пустой, Длина строки должна быть не меньше 10, Длина строки не должна быть больше 34, Поле не может быть null
      private Color eyeColor; //Поле может быть null
      private Country nationality; //Поле может быть null
      private Location location; //Поле не может быть null
    }
    public class Coordinates {
      private Long x; //Максимальное значение поля: 273, Поле не может быть null
      private Long y; //Максимальное значение поля: 343, Поле не может быть null
    }
    public class Location {
      private Long x; //Поле не может быть null
      private Integer y; //Поле не может быть null
      private Integer z; //Поле не может быть null
    }
    public enum Color {
      BLACK,
      BLUE,
      YELLOW,
      BROWN;
    }
    public enum Country {
      INDIA,
      VATICAN,
      THAILAND,
      NORTH_KOREA,
      JAPAN;
    }
    ```
    Веб-сервис должен удовлетворять следующим требованиям:
      - API, реализуемый сервисом, должен соответствовать рекомендациям подхода RESTful.
      - Необходимо реализовать следующий базовый набор операций с объектами коллекции: добавление нового элемента, получение элемента по ИД, обновление элемента, удаление элемента, получение массива элементов.
      - Операция, выполняемая над объектом коллекции, должна определяться методом HTTP-запроса.
      - Операция получения массива элементов должна поддерживать возможность сортировки и фильтрации по любой комбинации полей класса, а также возможность постраничного вывода результатов выборки с указанием размера и порядкового номера выводимой страницы.
      - Все параметры, необходимые для выполнения операции, должны передаваться в URL запроса.
      - Информация об объектах коллекции должна передаваться в формате **xml**.
      - В случае передачи сервису данных, нарушающих заданные на уровне класса ограничения целостности, сервис должен возвращать код ответа http, соответствующий произошедшей ошибке.

    Помимо базового набора, веб-сервис должен поддерживать следующие операции над объектами коллекции:
      - Вернуть один (любой) объект, значение поля passportID которого является максимальным.
      - Сгруппировать объекты по значению поля id, вернуть количество элементов в каждой группе.
      - Вернуть количество объектов, значение поля height которых меньше заданного.

    Эти операции должны размещаться на отдельных URL.

    **Второй веб-сервис** должен располагаться на URL `/demography`, и реализовывать ряд дополнительных операций, связанных с вызовом API первого сервиса:

      - `/eye-color/{eye-color}/percentage` : вывести долю людей с заданным цветом глаз в общей популяции (в процентах)
      - `/nationality/{nationality}/eye-color/{eye-color}/percentage` : вывести долю людей с заданным цветом глаз в пределах указанной национальности (в процентах)

    Эти операции также должны размещаться на отдельных URL.

    Для разработанной спецификации необходимо сгенерировать интерактивную веб-документацию с помощью Swagger UI. Документация должна содержать описание всех REST API обоих сервисов с текстовым описанием функциональности каждой операции. Созданную веб-документацию необходимо развернуть на сервере `helios`.
  license:
    name: ИТМО/ВТ
    url: https://se.ifmo.ru

servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: demography
    description: Demography operations
paths:
  /demography/eye-color/{eye-color}/percentage:
    get:
      tags:
        - demography
      summary: Get percentage of Persons with specified eye color
      description: Get percentage of Persons with specified eye color
      operationId: getPercentageOfPersonsByEyeColor
      parameters:
        - in: path
          name: eye-color
          schema:
            $ref: '#/components/schemas/Color'
          required: true
          description: Eye color of the persons
      responses:
        '200':
          description: Successful operation
          content:
            application/xml:
              schema:
                type: number
                xml:
                  name: percentage
        '400':
          description: Invalid Eye color
          content:
            application/xml:
              schema:
                type: string
                xml:
                  name: error
                example:
                  Invalid Eye color
        '405':
          description: No persons in store
          content:
            application/xml:
              schema:
                type: string
                xml:
                  name: error
                example:
                  No persons in store
      security:
        - backend_auth: []
  /demography/nationality/{nationality}/eye-color/{eye-color}/percentage:
    get:
      tags:
        - demography
      summary: Get percentage of Persons with specified nationality and eye color
      description: Get percentage of Persons with specified nationality and eye color
      operationId: getPercentageOfPersonsByNationalityAndEyeColor
      parameters:
        - in: path
          name: nationality
          schema:
            $ref: '#/components/schemas/Country'
          required: true
          description: Country of the persons
        - in: path
          name: eye-color
          schema:
            $ref: '#/components/schemas/Color'
          required: true
          description: Eye color of the persons
      responses:
        '200':
          description: Successful operation
          content:          
            application/xml:
              schema:
                type: number
                xml:
                  name: percentage
        '400':
          description: Invalid Nationality or Eye color
          content:
            application/xml:
              schema:
                type: string
                xml:
                  name: error
                example:
                  - Invalid Eye color
                  - Invalid Nationality
        '405':
          description: No persons in store
          content:
            application/xml:
              schema:
                type: string
                xml:
                  name: error
                example:
                  No persons in store
      security:
        - backend_auth: []
components:
  schemas:
    Country:
      type: string
      enum:
        - INDIA
        - VATICAN
        - THAILAND
        - NORTH_KOREA
        - JAPAN
    Color:
      type: string
      enum:
        - BLACK
        - BLUE
        - YELLOW
        - BROWN
    Location:
      type: object
      properties:
        x:
          type: integer
          format: int64
          example: 10
        y:
          type: integer
          format: int32
          example: 25
        z:
          type: integer
          format: int32
          example: 100
      xml:
        name: location
    Coordinates:
      type: object
      properties:
        x:
          type: integer
          format: int64
          maximum: 273
          example: 133
        y:
          type: integer
          format: int64
          maximum: 343
          example: 248
      xml:
        name: coordinates
    Person:
      type: object
      properties:
        id:
          type: integer
          format: int32
          minimum: 1
          description: Unique, auto-generated value
          example: 5
        name:
          type: string
          minLength: 1
          example: Ivan
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        creationDate:
          type: string
          description: java.time.ZonedDateTime, auto-generated value
        height:
          type: number
          format: double
          minimum: 0
          exclusiveMinimum: true
          example: 175
        passportID:
          type: string
          minLength: 10
          maxLength: 34
          example: 7515203784
        eyeColor:
          $ref: '#/components/schemas/Color'
        nationality:
          $ref: '#/components/schemas/Country'
        location:
          $ref: '#/components/schemas/Location'
      xml:
        name: person
  responses:
    UnauthorizedError:
      description: Authentication information is missing
  securitySchemes:
    backend_auth:
      type: http
      scheme: basic